name: SKY UX Pipeline

on:
  pull_request:
    branches: [master]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: Blackbaud-SteveBrush/skyux-libraries-action@v1.0.0-alpha.1
